'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Sparkles, Loader2 } from 'lucide-react'

interface AISummarySectionProps {
	content: string
	className?: string
}

const AISummarySection = ({ content }: AISummarySectionProps) => {
	const [isVisible, setIsVisible] = useState(false)
	const [summary, setSummary] = useState('')
	const [isLoading, setIsLoading] = useState(false)
	const [error, setError] = useState<string | null>(null)

	const generateSummary = async () => {
		if (isVisible && summary) {
			setIsVisible(false)
			return
		}
		if (summary && !isVisible) {
			setIsVisible(true)
			return
		}

		setIsLoading(true)
		setError(null)

		try {
			const response = await fetch('/api/summarize', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({ content }),
			})

			const data = await response.json()

			if (!response.ok) {
				throw new Error(data.error || 'Failed to generate summary')
			}

			setSummary(data.summary)
			setIsVisible(true)
		} catch (err) {
			setError(
				err instanceof Error ? err.message : 'Failed to generate summary',
			)
		} finally {
			setIsLoading(false)
		}
	}

	return (
		<div className='w-3/4 mx-auto my-5'>
			<Card className='p-4 bg-linear-to-br from-blue-50 to-indigo-50 border-blue-200 shadow-inner'>
				<div className='flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3'>
					<h3 className='text-base font-semibold text-gray-800 flex items-center'>
						<Sparkles className='w-5 h-5 mr-2 text-blue-500' />
						AI Analysis
					</h3>
					<Button
						onClick={generateSummary}
						disabled={isLoading}
						className='w-full sm:w-auto bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-full shadow-md transition duration-150 ease-in-out transform hover:scale-[1.02] focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50'
					>
						{isLoading ? (
							<>
								<Loader2 className='w-4 h-4 mr-2 animate-spin' />
								Generating Summary...
							</>
						) : isVisible ? (
							'Hide Summary'
						) : (
							'Summarize Post Content'
						)}
					</Button>
				</div>

				{/* Summary Result Area */}
				<div
					className={`transition-all duration-500 overflow-hidden ${
						isVisible ? 'max-h-96 opacity-100 mt-4' : 'max-h-0 opacity-0'
					}`}
				>
					<div className='text-sm text-gray-700 bg-white p-4 rounded-lg border border-blue-300 shadow-lg'>
						<p className='font-bold text-blue-600 mb-2'>Generated Summary:</p>
						<p className='text-gray-800 italic'>{summary}</p>
					</div>
					<p className='text-xs mt-2 text-gray-500 text-right'>
						*Generated by AI
					</p>
				</div>

				{/* Error Message */}
				{error && (
					<div className='mt-4 p-3 bg-red-50 border border-red-200 rounded-lg'>
						<p className='text-sm text-red-600'>{error}</p>
					</div>
				)}
			</Card>
		</div>
	)
}

export default AISummarySection
